<?php

return [

  // Betaling by Mubeen & GIGABAIT

  'title' => 'Betaling',
  'connecting' => 'Forbinder...',

  // Languages
  'us' => 'English',
  'id' => 'Indonesian',
  'hu' => 'Hungarian',
  'jp' => 'Japanese',
  'cz' => 'Czech',
  'de' => 'Deutsch',
  'nl' => 'Dutch',
  'es' => 'Spanish',
  'pt' => 'Portuguese',
  'fr' => 'French',
  'it' => 'Italian',
  'ru' => 'Russian',
  'tw' => 'Chinese',
  'pl' => 'Polish',
  'ua' => 'Ukrainian',

  // Nav Pages
  'billing_page' => 'Betaling',
  'balance_page' => 'Balance',
  'cart_page' => 'Kurv',
  'plan_page' => 'Mine pakker',
  'servers_page' => 'Servere',
  'console_page' => 'Konsol',
  'files_page' => 'Filer',
  'databases_page' => 'Databaser',
  'shedulers_page' => 'Planlægning',
  'users_page' => 'Brugere',
  'backups_page' => 'Backups',
  'network_page' => 'Netværk',
  'startup_page' => 'Opstart',
  'settings_page' => 'Indstillinger',
  'manage_page' => 'Administrer',
  'account_page' => 'Konto',
  'admin_page' => 'Admin',
  'out_page' => 'Log ud',
  'plugin_page' => 'Plugins',

  // Account
  'account_balance' => 'Konto balance',
  'paypal' => 'PayPal',
  'stripe' => 'Stripe',
  'billing_information' => 'Betalingsoplysninger',
  'amount_info' => 'Indtast det beløb, du ønsker at tilføje',
  'card_holder' => 'Navn på kortindehaver',
  'email' => 'Email',
  'caed_number' => 'Kortnummer',
  'cvv' => 'CVV',
  'pay_now' => 'Betal nu',
  'username' => 'Brugernavn',
  'address' => 'Adresse',
  'first_name' => 'Fornavn',
  'last_name' => 'Efternavn',
  'city' => 'By',
  'country' => 'Land',
  'postal_code' => 'Postnummer',
  'update_billing_nformation' => 'Opdater betalingsoplysninger',
  'edit_account' => 'Rediger konto',
  'account_api' => 'Konto API',
  'billing_balance' => 'Betalingsbalance',
  'admin_area' => 'Admin område',
  'dark_mode' => 'Mørkt tema',
  'light_mode' => 'Lyst tema',
  'logout' => 'Log ud',
  'register' => 'Registrer',
  'login' => 'Log ind',

  // Kurv
  'checkout' => 'Tjek ud',
  'game' => 'Spil',
  'billed' => 'Faktureret',
  'actions' => 'Handlinger',
  'empty_cart' => 'Kurv er tom.',
  'place_order' => 'Bekræft ordre',
  'plan_name' => 'Plan navn',
  'total_order' => 'Total ordre: ',
  'cancel' => 'Annullér',
  'confirm' => 'Bekræft',
  'confirm_place_order_info' => 'Efter at have trykket "Bekræft ordre", vil din ordre blive afgivet og beløbet vil blive trukket fra din nuværende balance.',

  // Betaling
  'date_label' => 'Dato',
  'price_label' => 'Pris',
  'view_plan' => 'Se Planer',
  'view_invoices' => 'Se Fakturaer',
  'extend' => 'Forlæng',
  'days_for' => 'dage for',
  'deleted' => 'slettet',
  'pay' => 'Betal',
  'are_you_sure' => 'Er du sikker?',
  'remove' => 'Fjern',
  'close' => 'Luk',

  // Plans
  'plans_labal' => 'Planer',
  'add_to_cart' => 'Tilføj til Kurv',
  'description' => 'Beskrivelse',
  'monthly' => 'Månedligt',
  'year' => 'År',
  'quarterly' => 'Kvartalsvis',
  'unlimited' => 'Ubegrænset',
  'days' => 'dage',
  'cpu' => 'CPU:',
  'ram' => 'RAM:',
  'storage' => 'Lagring:',
  'backup' => 'Backup(s)',
  'database' => 'Database(r)',
  'exstra_ports' => 'Ekstra Port(e)',
  'plugin_integration' => 'Plugins installation',

  // Invoices
  'invoice_date' => 'Faktura Dato:',
  'due_date' => 'Forfaldsdato:',
  'invoice_price' => 'Pris:',
  'renew_plan' => 'Forny Plan',
  'viewing_invoices' => 'Se Fakturaer',
  'request_cancellation' => 'Anmod om Annullering',
  'extend_plan_info' => 'Ved at fuldføre betalingen vil du forlænge din plan, venligst klik på "Betal" knappen nedenfor for at forlænge.<br> Efter at betalingsknappen er blevet trykket, vil vi automatisk trække det tilsvarende beløb fra din saldo. <br>',
  'remove_plan_info' => 'Anmodning om annullering vil slette serveren, slette alle filer uden mulighed for at gendanne. Hvis serveren er aktiv, mister du pengene brugt uden mulighed for at få dem tilbage!',

  // Success
  'plan_added_cart' => 'Plan tilføjet til kurv',
  'server_create_success' => 'Din server er blevet oprettet med succes, gå til Mine Planer for mere information.',
  'stripe_status_url' => 'Status URL: ',
  'success' => 'Succes',

  // Errors
  'err_remove_game' => 'Beklager. Du skal først fjerne alle planer, der hører til dette spil.',
  'err_plan_limit' => 'Beklager. Du har nået en grænse. Du må kun købe følgende mængde: ',
  'err_create_server' => 'Der opstod en fejl under oprettelse af en ny server.',
  'err_user_balance' => 'Der er ikke nok balance på din konto til at foretage dette køb.',
  'err_plan_exist' => 'Planen er fjernet fra din kurv.',
  'err_plans_in_game' => 'Der er ingen planer til dette spil.',
  'error' => 'Fejl',
  'error_full_node' => 'Denne server er fuld!!! Informér venligst administrator',

  // Domain
  'subdomain_integration' => 'Underdomæne support',
  'server_ip_address' => 'Server IP-adresse',
  'memory' => 'Hukommelse',
  'plan' => 'Plan',
  'plan_subdomain' => 'Plan underdomæne',
  'zone' => 'Zone',
  'invoices' => 'Fakturaer',
  'plan_error' => 'Din plan understøtter ikke oprettelse af et underdomæne',

  // Portal
  'portal_sw_mode' => 'Skift tilstand',
  'portal' => 'Portal',
  'features' => 'Funktioner',
  'games' => 'Spil',
  'about' => 'Om',
  'faqs' => 'Ofte stillede spørgsmål',
  'discord' => 'Discord',
  'minimize' => 'Minimer',
  'footer_contact' => '<p>A108 Adam Street <br>New York, NY 535022<br>United States <br><br><strong>Telefon:</strong> +1 5589 55488 55<br><strong>Email:</strong> info@example.com<br></p>',
  'useful_links' => 'Nyttige links',
  'our_services' => 'Vores tjenester',
  'about_us' => 'Om os',
  'about_us_content' => 'Skriv noget om din vært her.',
  'about_us_title' => 'Hvorfor vælge os?',
  'about_us_text1' => 'Vi tilbyder et hav af fede funktioner, vi har dig dækket!',
  'about_us_text2' => "<li><i class='bx bx-check-double' ></i> Brugerhåndtering</li><li><i class='bx bx-check-double' ></i> Pluginhåndtering</li><li><i class='bx bx-check-double' ></i> Filhåndtering</li>",
  'get_started' => 'Kom i gang',
  'game_panel' => 'Spilpanel',
  'game_panel_desc' => 'Vores intuitive spilpanel giver en nem måde at navigere gennem panelet på. Faktureringsområdet er direkte integreret i panelet. Panelet er udstyret med alle de funktioner, du nogensinde vil få brug for, og en awesome moderne design bygget på Pterodactyl.',
  'console_desc' => 'Se de seneste logfiler i konsollen, send kommandoer eller håndter strømfunktioner.',
  'pl_installer' => 'Plugin-installationsprogram',
  'pl_installer_desc' => 'Installer over 65000+ plugins med bare et enkelt klik',
  'schedules' => 'Planer',
  'schedules_desc' => 'Planlæg specielle begivenheder, opgaver eller strømfunktioner.',
  'happy_clients' => 'Tilfredse kunder',
  'active_pans' => 'Aktive abonnementer',
  'active_servers' => 'Aktive servere',
  'uptime' => '% Uptime',
  'register_now' => 'Registrer nu',
  'register_now_desc' => 'Registrer din konto og få din server i gang på ingen tid!',
  'create_account' => 'Opret konto',
  'faq_section_title' => 'Ofte stillede spørgsmål',
  'faq_section_title_desc' => 'Nedenfor er en liste med de mest stillede spørgsmål fra vores kunder.',
  'features_desc' => 'Vores Game Panel har et bredt udvalg af indbyggede funktioner',
  'plugins_manager' => 'Plugin Manager',
  'plugins_manager_desc' => 'Vælg mellem over 60000 plugins, og installer med kun et enkelt klik',
  'file_manager' => 'Fil Manager',
  'file_manager_desc' => 'Vores fil manager giver dig mulighed for at uploade, oprette, downloade, sætte tilladelser, zip & unzip filer og administrer dem på en nem måde',
  'backup_manager' => 'Backup Manager',
  'backup_manager_desc' => 'Vores dashboard giver dig mulighed for at tage sikkerhedskopier af dine filer når som helst',
  'user_manager' => 'Bruger Manager',
  'user_manager_desc' => 'Inviter venner eller staff til din dashboard. Du kan sætte bestemte tilladelser per medlem',
  'schedule_manager' => 'Tidsplan Manager',
  'schedule_manager_desc' => 'Vores Tidsplan system giver dig mulighed for at sætte tidsbestemte strømstyringer, sikkerhedskopier eller opgaver',
  'database_manager' => 'Database Manager',
  'database_manager_desc' => 'Generer MySQL Databaser, opret nye allocationer og meget mere',
  'game_list_desc_1' => 'Vælg spillet du ønsker at se planer for',
  'game_list_desc_2' => 'Der er ingen spil tilgængelige, opret dem i admin området.',
  'game_plans_section_text' => 'Nedenfor er en liste over tilgængelige planer for dette spil. Vælg planen der passer dig bedst.',
  'game_plans_section_text_empty' => 'Der er ingen spil tilgængelige, opret dem i admin området.',
  'team' => 'Hold',
  'team_content' => 'Vores team består af udviklere, community moderatorer og support managers.',
  'welcome_back' => 'Velkommen tilbage,',
  'panel_dreams' => 'Panel af dine drømme',
  'panel_dreams_text' => 'Administrer din server med et nemt-at-bruge Game Panel.',
  'manage_servers' => 'Administrer Servere',
  'dashboard' => 'Dashboard',
  'easy_manage' => 'Let at administrere',
  'easy_manage_text' => 'Vores Dashboard gør det nemt at administrere din server.',
  'portal_sw_mode_desc' => 'Vælg mellem lyst og mørkt mode, vælg det der føles rigtigt for dig.',
  'user_anagement' => 'Brugeradministration',
  'user_anagement_desc' => 'Inviter venner eller staff til at deltage i serveradministrationen, sæt specifikke tilladelser per bruger.',
  
  // Gift Card
  'gift_card' => 'Gavekort',
  'gift_card_code' => 'Gavekortkode',
  'gift_card_not_exist' => 'Gavekort eksisterer ikke eller dets grænse er udløbet',
  'gift_card_used_error' => 'Du har allerede brugt dette gavekort',
  'gift_card_used_success' => 'Din balance er blevet opdateret'
];
